*&---------------------------------------------------------------------*
*&  Include  Z01_TABSTRIP_WIZZARD_I01
*&---------------------------------------------------------------------*

*&SPWIZARD: INPUT MODULE FOR TS 'MY_TABSTRIP'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: GETS ACTIVE TAB
MODULE MY_TABSTRIP_ACTIVE_TAB_GET INPUT.
  OK_CODE = SY-UCOMM.
  CASE OK_CODE.
    WHEN C_MY_TABSTRIP-TAB1.
      G_MY_TABSTRIP-PRESSED_TAB = C_MY_TABSTRIP-TAB1.
    WHEN C_MY_TABSTRIP-TAB2.
      G_MY_TABSTRIP-PRESSED_TAB = C_MY_TABSTRIP-TAB2.
    WHEN C_MY_TABSTRIP-TAB3.
      G_MY_TABSTRIP-PRESSED_TAB = C_MY_TABSTRIP-TAB3.
    WHEN OTHERS.
*&SPWIZARD:      DO NOTHING
  ENDCASE.
ENDMODULE.
